Repository wirecard/shopware-ee, pull requests merged in 2020-05, with the labels that each got.

#194 Add changelog
  CHANGELOG.md
  SHOPVERSIONS
Labels: ready for review

#195 Remove autoload and installer name from composer json
  composer.json
Labels: ready for merge

#185 Rc 1.4.0 minor
  .github/pr-labeler.yml
  .github/prlint.json
  CHANGELOG.md
  Components/Data/OrderSummary.php
  Components/Mapper/AccountInfoMapper.php
  Components/Mapper/BasketMapper.php
  Components/Mapper/RiskInfoMapper.php
  Components/Mapper/UserMapper.php
  Components/Payments/CreditCardPayment.php
  Components/Services/NotificationHandler.php
  Components/Services/PaymentHandler.php
  Components/Services/ThreedsHelper.php
  Components/Services/TransactionManager.php
  Controllers/Backend/WirecardElasticEngineTransactions.php
  Controllers/Frontend/WirecardElasticEnginePayment.php
  Models/CreditCardVault.php
  Models/Transaction.php
  README.md
  Resources/config.xml
  Resources/services.xml
  Resources/views/frontend/_public/src/img/Alipay.png
  SHOPVERSIONS
  Tests/Functional/Controllers/Frontend/WirecardElasticEnginePaymentTest.php
  Tests/Functional/Controllers/Frontend/testdata/index-basket.php
  Tests/Selenium/Payments/PaypalTest.js
  Tests/Unit/Components/Data/OrderSummaryTest.php
  Tests/Unit/Components/Mapper/AccountInfoMapperTest.php
  Tests/Unit/Components/Mapper/BasketMapperTest.php
  Tests/Unit/Components/Mapper/RiskInfoMapperTest.php
  Tests/Unit/Components/Mapper/UserMapperTest.php
  Tests/Unit/Components/Payments/CreditCardPaymentTest.php
  Tests/Unit/Components/Services/ThreedsHelperTest.php
  Tests/Unit/Models/CreditCardVaultTest.php
  WirecardElasticEngine.php
  composer.json
  plugin.xml
Labels: minor

#184 Use Wirecard GitHub actions and improve pr labeler
  .github/pr-labeler.yml
  .github/prlint.json
  .github/workflows/change-release-version.yml
  .github/workflows/create_release.yml
Labels: no-release

#196 Remove SHOPVERSIONS file
  .github/artifact-configuration.json
  .travis.yml
  SHOPVERSIONS
Labels: no-release

#197 Update 'validate travis' pipeline to run only on travis file change
  .github/workflows/validate-travis-file.yml
Labels: no-release

#198 Update compatibilities
  .travis.yml
  CHANGELOG.md
  README.md
  plugin.xml
Labels: no-release

#200 Clean up travis file and remove compatibility checks
  .bin/compatible-shop-releases.txt
  .bin/get-latest-shop-release-versions.sh
  .bin/update-shop-release-versions.sh
  .travis.yml
Labels: no-release, ready for review
