Repository wirecard/shopware-ee, pull requests merged in 2020-08, with the labels that each got.

#213 Tpwdcee 5395 feature Remove Masterpass und UnionPay International
  Components/Payments/MasterpassPayment.php
  Components/Payments/UnionpayInternationalPayment.php
  Components/Services/PaymentFactory.php
  Resources/config.xml
  Resources/config.xml.tpl
  Resources/languages/de_DE.json
  Resources/languages/en_US.json
  Resources/snippets/frontend/wirecard_elastic_engine/payments.ini
  Resources/snippets/frontend/wirecard_elastic_engine/payments.ini.tpl
  Resources/views/frontend/checkout/change_payment.tpl
  Tests/Functional/Components/Payments/MasterpassPaymentTest.php
  Tests/Functional/Components/Payments/UnionpayInternationalPaymentTest.php
  Tests/Selenium/Payments/MasterpassTest.js
  Tests/Selenium/Payments/UpiTest.js
  Tests/Selenium/config.js
  Tests/Unit/Components/Payments/MasterpassPaymentTest.php
  Tests/Unit/Components/Payments/UnionpayInternationalPaymentTest.php
  Tests/Unit/Components/Payments/testdata/upi-requestdata.json
  package.json
Labels: ready for merge

#211 [Tpwdcee 7048] Remove live chat
  Resources/config.xml
  Resources/config.xml.tpl
  Resources/menu.xml
  Resources/menu.xml.tpl
  Resources/views/backend/wirecard_elastic_engine_transactions/chat.tpl
  Subscriber/BackendSubscriber.php
Labels: ready for merge

#210 [TPWDCEE-6960] fix challange indicator ui to use strings wich are later mapped
  Components/Services/ThreedsHelper.php
  Resources/config.xml
  Resources/config.xml.tpl
Labels: ready for merge

#212 Tpwdcee 7151 feature
  Components/Services/TransactionManager.php
Labels: ready for testing

#209 Create RC 1.4.2 patch
  .bin/compatible-shop-releases.txt
  .travis.yml
  CHANGELOG.md
  Components/Payments/MasterpassPayment.php
  Components/Payments/UnionpayInternationalPayment.php
  Components/Services/PaymentFactory.php
  Components/Services/ThreedsHelper.php
  Components/Services/TransactionManager.php
  Resources/config.xml
  Resources/config.xml.tpl
  Resources/languages/de_DE.json
  Resources/languages/en_US.json
  Resources/menu.xml
  Resources/menu.xml.tpl
  Resources/snippets/frontend/wirecard_elastic_engine/payments.ini
  Resources/snippets/frontend/wirecard_elastic_engine/payments.ini.tpl
  Resources/views/backend/wirecard_elastic_engine_transactions/chat.tpl
  Resources/views/frontend/checkout/change_payment.tpl
  Subscriber/BackendSubscriber.php
  Tests/Functional/Components/Payments/MasterpassPaymentTest.php
  Tests/Functional/Components/Payments/UnionpayInternationalPaymentTest.php
  Tests/Selenium/Payments/MasterpassTest.js
  Tests/Selenium/Payments/UpiTest.js
  Tests/Selenium/common.js
  Tests/Selenium/config.js
  Tests/Unit/Components/Payments/MasterpassPaymentTest.php
  Tests/Unit/Components/Payments/UnionpayInternationalPaymentTest.php
  Tests/Unit/Components/Payments/testdata/upi-requestdata.json
  package.json
  plugin.xml
Labels: patch, work in progress
