Repository wirecard/shopware-ee, pull requests merged in 2020-04, with the labels that each got.

#176 Add change release version GitHub action
  .github/workflows/change-release-version.yml
Labels: no-release, ready for approval

#178 Exchange alipay cross-border logo
  Resources/views/frontend/_public/src/img/Alipay.png
Labels: ready for review

#180 Tpwdcee 6471 feature
  Controllers/Frontend/WirecardElasticEnginePayment.php
  composer.json
Labels: ready for review

#181 Add dependabot to PR lint
  .github/pr-labeler.yml
  .github/prlint.json
Labels: no-release

#182 Add github action to validate travis file
  .github/workflows/validate-travis-file.yml
Labels: no-release

#177 Send order id if additional information is disabled
  Components/Services/PaymentHandler.php
Labels: ready for review
