Repository wirecard/shopware-ee, pull requests merged in 2020-02, with the labels that each got.

#157 TPWDCEE-5761
  Components/Services/NotificationHandler.php
  Components/Services/TransactionManager.php
  Models/Transaction.php
Labels: ready for review

#165 Add feature option to PR Lint
  .github/prlint.json
Labels: no-release

#163 Reduce payment config data sent with support email
  Components/Mail/SupportMail.php
Labels: no-release, ready for merge

#169 Disable nightly compatibility checks
  .travis.yml
Labels: no-release, ready for approval

#166 Rc 1.3.10 patch
  CHANGELOG.md
  Components/Mail/SupportMail.php
  SHOPVERSIONS
  plugin.xml
Labels: patch

#171 Remove unrelevant badges
  README.md
Labels: no-release

#172 Tpwdcee 6112 configuration
  .bin/prepare-release-files.sh
  .github/artifact-configuration.json
  .github/workflows/create_release.yml
Labels: no-release

#173 Improve PayPal test and add new credentials
  Tests/Selenium/Payments/PaypalTest.js
  Tests/Selenium/config.js
Labels: no-release, ready for approval
